### ISSUE TITLE
currentTarget should be nullable

### ISSUE THREAD

**Issue by coot** [purescript-web/purescript-dom#110]
Myabe that specifc to React but the native event can have currentTarget null.

![screenshot from 2017-06-27 21-49-39](https://user-images.githubusercontent.com/698209/27606969-93f053b6-5b82-11e7-8f5f-fd6784f5b6fa.png)

**Comment by garyb** [comment]
Hmm, that is annoying. It's `null` if an event is created but hasn't come through the DOM - it can't be null if it's received otherwise, as it refers to the thing that `addEventListener` was attached to! But yeah, because it's possible, it should be typed as such.

**Comment by coot** [comment]
True, if I just do
```
m = new MouseEvent('click')
```
Then `target`, `currentTarget`, `relatedTarget`,  `view` are all set to `null`, since there isn't any value they could yet have. But the event I originally posted has fired.  It only missing the `currentTarget` maybe because it's after bubbling phase.

**Comment by garyb** [comment]
Will be resolved in the release for 0.12.
