### ISSUE TITLE
Add `slice` for Blob

### ISSUE THREAD

**Issue by safareli** [purescript-web/purescript-dom#125]
https://developer.mozilla.org/en-US/docs/Web/API/Blob/slice

**Comment by safareli** [comment]
The `slice` takes Integer number but using `Int` will not be correct because its range is smaller, then what this function can handle. 
We should 

- either use Number, or 
- define a new data type `Data.Int.Long` or similar

if we define `Data.Int.Long` it should be like Int but instead of `(n | 0) === n` we should use `Number.IsSafeInteger(n)`. 

related https://github.com/purescript/purescript-integers/issues/28

**Comment by safareli** [comment]
Regarding `Data.Int.Long`  there actually is `Data.Int53` in `purescript-int-53` which I think we should use.

**Comment by garyb** [comment]
`Int53` would definitely be suitable for this, but we try to avoid depending on "private" libraries in `-contrib` libraries, as it gets awkward if they become unmaintained etc.

Maybe we can do something here with `StartByte` / `EndByte` style newtypes that have smart constructors to perform the necessary rounding and clamping from `Number` instead.
