### ISSUE TITLE
document testing

### ISSUE THREAD

**Issue by matthewleon** [purescript-web/purescript-dom#130]
Tests fail on my machine with repeated `ReferenceError: window is not defined`.

I imagine the test are meant to run in the browser, rather than Node. Can this be documented?

**Comment by garyb** [comment]
How are you running them? They should work with `yarn test` / `npm test` as the phantomjs runtime is used then. It's just set up to use the `--runtime` flag with `pulp`.

**Comment by matthewleon** [comment]
Ah okay. I should have figured that out. I was using `pulp test`.
