### ISSUE TITLE
HTMLCollection operations

### ISSUE THREAD

**Issue by LiamGoodacre** [purescript-web/purescript-dom#142]
There are various ways of getting an `HTMLCollection` but seemingly no way of doing anything with one once you have it.

**Comment by garyb** [comment]
These appear to have been added at some point.

**Comment by LiamGoodacre** [comment]
Wait, where?  I still can't find them anywhere.

**Comment by garyb** [comment]
These? https://github.com/purescript-web/purescript-dom/blob/master/src/DOM/Node/HTMLCollection.purs

**Comment by garyb** [comment]
Maybe the location is confusing, since it's `HTMLCollection` but part of the `DOM` spec rather than the `HTML` spec? 🤦‍♂️

**Comment by LiamGoodacre** [comment]
Right: I'm just very bad at searching. :sweat_smile:
